ask_yourself: "&cYou can ask Yourself!!"

Start_Duel: "&9Duel start!"

Deny_Duel: "&7You deny Duel"

Player_Deny_Duel: "Player &e<PlayerDenyDuel> &rdeny duel!"

Create_Arena: "You create arena &a<ArenaName>"

No_Permission: "&4You don't have permission"

Player_Already_Have_Requests: "&cAttention this player already has a duel request in progress"

Ask_Player: "&7You just asked a duel with &e<player>"

Receive_Duel: "&9You have just received a duel request from &r<player>"

Player_Not_Connected: "Player &c<PlayerNotConnected>&f it's not connected or not exist"

HelpCommand:
  - "&6--------------&e Duel &6----------------"
  - "&e/&rduel <player>"
  - "&e/&rduel <accept/deny>"
  - "&e/&rduel createarena <loc1> <loc2> <ArenaName>"
  - "&e/&rduel createarena <X,Y,Z> <X,Y,Z> <ArenaName>"
  - "&6------------------------------------"

#Stuff for duel.
Helmet: "DIAMOND_HELMET"
Chestplate: "DIAMOND_CHESTPLATE"
Leggings: "DIAMOND_LEGGINGS"
Boots: "DIAMOND_BOOTS"
Sword: "DIAMOND_SWORD"